[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 3

[profile.ci]
fuzz_runs = 10000
verbosity = 4

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options